# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

volumes:
  postgres_data:
      driver: local
  authr_data:
      driver: local

services:
  microsvc-gate:
    image: microsvc-gate
    container_name: microsvc-gate
    build: ./microsvc-gate
    ports:
        # - '5101:80'
        - '5100:443'
    environment:
    #     - ASPNETCORE_URLS=https://+;http://+
    #     - ASPNETCORE_HTTPS_PORT=5100
        - ASPNETCORE_ENVIRONMENT=docker-dev
        - ASPNETCORE_Kestrel__Certificates__Default__Password=noonan
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microsvc-gate.pfx  
    volumes:
        - '${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets'
        - '${USERPROFILE}\.aspnet\https:/https'
  microsvc-authr:
    container_name: nexus-microsvc-authr
    image: nexus-microsvc-authr
    build: ./microsvc-authr
    ports:
        - '5030:80'
    environment:
        - ASPNETCORE_ENVIRONMENT=Development


  userdb:
    image: postgres
    container_name: userdb
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5436:5432
  
  microsvcfilemeta:
    image: microsvc-filemeta
    container_name: microsvc-filemeta
    build:
      context: .
      dockerfile: microsvc-filemeta/Dockerfile
    ports:
      - 5102:5102
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  seq:
    image: datalust/seq:latest
    container_name: nexlog
    ports:
      - 5109:80
    environment:
      - ACCEPT_EULA=Y
  postgres:
      image: postgres
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres


  # microsvc-nddsgate:
  #   image: microsvc-nddsgate
  #   container_name: microsvc-nddsgate
  #   build: ./microsvc-nddsgate
  #   ports:
  #       - '5101:80'
  #       - '5100:443'
  #   environment:
  #       - ASPNETCORE_URLS=https://+;http://+
  #       - ASPNETCORE_HTTPS_PORT=5100
  #       - ASPNETCORE_ENVIRONMENT=Development
  #   volumes:
  #       - '${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets'
  #       - '${USERPROFILE}\.aspnet\https:/root/.aspnet/https/'
  # gate1:
  #   image: gate1
  #   container_name: gate1
  #   build: ./gate1
  #   ports:
  #       - '5901:80'
  #       - '5900:443'
  #   environment:
  #       - ASPNETCORE_URLS=https://+;http://+
  #       # - ASPNETCORE_HTTPS_PORT=5900
  #       - ASPNETCORE_ENVIRONMENT=Development
  #   volumes:
  #       - '${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets'
  #       - '${USERPROFILE}\.aspnet\https:/root/.aspnet/https/'
  # ocgate:
  #   image: oc-gate
  #   container_name: oc-gate
  #   build:
  #     context: .
  #     dockerfile: oc-gate/Dockerfile
  #   ports:
  #     - 5100:5100
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   volumes:
  #     - ~/.vsdbg:/remote_debugger:rw



