# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ocgate:
    image: ocgate
    build:
      context: .
      dockerfile: oc-gate/Dockerfile
    ports:
      - 5100:5100
