### Get Test 1 AuthN Token from Keycloak with U/P
POST http://localhost:8080/auth/realms/fakedds/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=testapp&username=test1&password=test1

### Get Test 2 AuthN Token from Keycloak with U/P
POST http://localhost:8080/auth/realms/fakedds/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=testapp&username=test2&password=test2


### Get Test 1 File Meta Throuhg GW
get http://localhost/FileMeta
Content-Type: application/json
Authorization: bearer {{$dotenv Test1AuthNToken}}

### Get Test 2 File Meta Throuhg GW
get http://localhost/FileMeta
Content-Type: application/json
Authorization: bearer {{$dotenv Test2AuthNToken}}



